# Generated by Django 2.1.2 on 2018-10-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('honey', '0002_auto_20181028_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honey.Honey')),
            ],
            options={
                'verbose_name': '工作队列',
                'verbose_name_plural': '工作队列',
            },
        ),
    ]
