# Generated by Django 2.1.2 on 2018-10-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='节点名称')),
                ('load', models.IntegerField(default=0, verbose_name='负载')),
                ('server', models.CharField(max_length=64, verbose_name='服务器地址')),
                ('server_port', models.IntegerField(verbose_name='服务器端口')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('method', models.CharField(max_length=64, verbose_name='算法')),
                ('obfs', models.CharField(default='', max_length=32, verbose_name='混淆')),
                ('obfs_param', models.CharField(default='', max_length=64, verbose_name='混淆参数')),
                ('protocol', models.CharField(default='', max_length=64, verbose_name='协议')),
                ('protocol_param', models.CharField(default='', max_length=64, verbose_name='协议参数')),
                ('ss_version', models.CharField(default='SSR', max_length=16, verbose_name='SS 版本')),
            ],
            options={
                'verbose_name': '蜂蜜',
                'verbose_name_plural': '蜂蜜',
            },
        ),
        migrations.CreateModel(
            name='Honeycomb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='用户名')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('remaining_amount', models.FloatField(default=0, verbose_name='剩余流量')),
                ('is_checkin', models.BooleanField(default=False, verbose_name='签到')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='最后修改')),
            ],
            options={
                'verbose_name': '蜂巢',
                'verbose_name_plural': '蜂巢',
            },
        ),
        migrations.AddField(
            model_name='honey',
            name='honeycomb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honey.Honeycomb'),
        ),
    ]
