# Generated by Django 2.1.2 on 2018-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeycomb',
            name='email',
            field=models.CharField(max_length=64, unique=True, verbose_name='邮箱'),
        ),
    ]
