# Generated by Django 2.1.2 on 2018-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0002_auto_20181028_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeycomb',
            name='subscription_url',
            field=models.URLField(null=True, verbose_name='订阅地址'),
        ),
    ]
